// generated by 'threeport-sdk gen' - do not edit

package v0

// Tabler allows custom table names for objects in the Threeport database.
type Tabler interface {
	TableName() string
}

// TableName sets the name of the table for the WordpressDefinition objects in the database.
func (WordpressDefinition) TableName() string {
	return "lander2k2_com_v0_wordpress_definitions"
}

// TableName sets the name of the table for the WordpressInstance objects in the database.
func (WordpressInstance) TableName() string {
	return "lander2k2_com_v0_wordpress_instances"
}
