// generated by 'threeport-sdk gen' - do not edit

package v0

import tpapiserver_lib "github.com/threeport/threeport/pkg/api-server/lib/v0"

var (
	WordpressDefinitionTaggedFields = make(map[string]*tpapiserver_lib.FieldsByTag)
	WordpressInstanceTaggedFields   = make(map[string]*tpapiserver_lib.FieldsByTag)
)
