// generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package migrations

import (
	"context"
	"database/sql"
	"fmt"
	goose "github.com/pressly/goose/v3"
	v0 "wordpress-threeport-module/pkg/api/v0"
)

func init() {
	goose.AddMigrationNoTxContext(Up000001, Down000001)
}

func Up000001(ctx context.Context, db *sql.DB) error {
	gormDb, err := getGormDbFromContext(ctx)
	if err != nil {
		return err
	}

	if err := gormDb.AutoMigrate(dbInterfaces000001()...); err != nil {
		return fmt.Errorf("could not run gorm AutoMigrate: %w", err)
	}

	return nil
}

func Down000001(ctx context.Context, db *sql.DB) error {
	gormDb, err := getGormDbFromContext(ctx)
	if err != nil {
		return err
	}

	tablesToDrop := dbInterfaces000001()
	for _, table := range tablesToDrop {
		if err := gormDb.Migrator().DropTable(table); err != nil {
			return fmt.Errorf("could not drop table with gorm db: %w", err)
		}
	}

	return nil
}

func dbInterfaces000001() []interface{} {
	return []interface{}{
		&v0.WordpressDefinition{},
		&v0.WordpressInstance{},
	}
}
