// generated by 'threeport-sdk gen' - do not edit

package wordpress

// The name and description of the NATS bucket used for wordpress object locks
const (
	LockBucketName  = "wordpressLock"
	LockBucketDescr = "contains locks on wordpress objects"
)
