// generated by 'threeport-sdk gen' - do not edit

package wordpress

import (
	"errors"
	"fmt"
	tpapi_lib "github.com/threeport/threeport/pkg/api/lib/v0"
	tpapi_v0 "github.com/threeport/threeport/pkg/api/v0"
	tpclient_lib "github.com/threeport/threeport/pkg/client/lib/v0"
	controller "github.com/threeport/threeport/pkg/controller/v0"
	event "github.com/threeport/threeport/pkg/event/v0"
	notifications "github.com/threeport/threeport/pkg/notifications/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"
	api_v0 "wordpress-threeport-module/pkg/api/v0"
	client_v0 "wordpress-threeport-module/pkg/client/v0"
)

// WordpressDefinitionReconciler reconciles system state when a WordpressDefinition
// is created, updated or deleted.
func WordpressDefinitionReconciler(r *controller.Reconciler) {
	r.ShutdownWait.Add(1)
	reconcilerLog := r.Log.WithValues("reconcilerName", r.Name)
	reconcilerLog.Info("reconciler started")
	shutdown := false

	// create a channel to receive OS signals
	osSignals := make(chan os.Signal, 1)
	lockReleased := make(chan bool, 1)

	// register the os signals channel to receive SIGINT and SIGTERM signals
	signal.Notify(osSignals, syscall.SIGINT, syscall.SIGTERM)

	for {
		// create a fresh log object per reconciliation loop so we don't
		// accumulate values across multiple loops
		log := r.Log.WithValues("reconcilerName", r.Name)

		if shutdown {
			break
		}

		// check for shutdown instruction
		select {
		case <-r.Shutdown:
			shutdown = true
		default:
			// pull message off queue
			msg := r.PullMessage()
			if msg == nil {
				continue
			}

			// consume message data to capture notification from API
			notif, err := notifications.ConsumeMessage(msg.Data)
			if err != nil {
				log.Error(
					err, "failed to consume message data from NATS",
					"msgData", string(msg.Data),
				)
				r.RequeueRaw(msg)
				log.V(1).Info("wordpress definition reconciliation requeued with identical payload and fixed delay")
				continue
			}

			// determine the correct object version from the notification
			var wordpressDefinition tpapi_lib.ReconciledThreeportApiObject
			switch notif.ObjectVersion {
			case "v0":
				wordpressDefinition = &api_v0.WordpressDefinition{}
			default:
				log.Error(errors.New("received unrecognized version of wordpress definition object"), "")
				r.RequeueRaw(msg)
				log.V(1).Info("wordpress definition reconciliation requeued with identical payload and fixed delay")
				continue
			}

			// decode the object that was sent in the notification
			if err := wordpressDefinition.DecodeNotifObject(notif.Object); err != nil {
				log.Error(err, "failed to marshal object map from consumed notification message")
				r.RequeueRaw(msg)
				log.V(1).Info("wordpress definition reconciliation requeued with identical payload and fixed delay")
				continue
			}
			log = log.WithValues("wordpressDefinitionID", wordpressDefinition.GetId())

			// back off the requeue delay as needed
			requeueDelay := controller.SetRequeueDelay(
				notif.CreationTime,
			)

			// check for lock on object
			locked, ok := r.CheckLock(wordpressDefinition)
			if locked || ok == false {
				r.Requeue(wordpressDefinition, requeueDelay, msg)
				log.V(1).Info("wordpress definition reconciliation requeued")
				continue
			}

			// set up handler to unlock and requeue on termination signal
			go func() {
				select {
				case <-osSignals:
					log.V(1).Info("received termination signal, performing unlock and requeue of wordpress definition")
					r.UnlockAndRequeue(wordpressDefinition, requeueDelay, lockReleased, msg)
				case <-lockReleased:
					log.V(1).Info("reached end of reconcile loop for wordpress definition, closing out signal handler")
				}
			}()

			// put a lock on the reconciliation of the created object
			if ok := r.Lock(wordpressDefinition); !ok {
				r.Requeue(wordpressDefinition, requeueDelay, msg)
				log.V(1).Info("wordpress definition reconciliation requeued")
				continue
			}

			// retrieve latest version of object
			var latestWordpressDefinition tpapi_lib.ReconciledThreeportApiObject
			var getLatestErr error
			switch notif.ObjectVersion {
			case "v0":
				latestObject, err := client_v0.GetWordpressDefinitionByID(
					r.APIClient,
					r.APIServer,
					wordpressDefinition.GetId(),
				)
				latestWordpressDefinition = latestObject
				getLatestErr = err
			default:
				getLatestErr = errors.New("received unrecognized version of wordpress definition object")
			}

			// check if error is 404 - if object no longer exists, no need to requeue
			if errors.Is(getLatestErr, tpclient_lib.ErrObjectNotFound) {
				log.Info("object no longer exists - halting reconciliation")
				r.ReleaseLock(wordpressDefinition, lockReleased, msg, true)
				continue
			}
			if getLatestErr != nil {
				log.Error(getLatestErr, "failed to get wordpress definition by ID from API")
				r.UnlockAndRequeue(wordpressDefinition, requeueDelay, lockReleased, msg)
				continue
			}
			wordpressDefinition = latestWordpressDefinition

			// determine which operation and act accordingly
			switch notif.Operation {
			case notifications.NotificationOperationCreated:
				if wordpressDefinition.ScheduledForDeletion() != nil {
					log.Info("wordpress definition scheduled for deletion - skipping create")
					break
				}
				var operationErr error
				var customRequeueDelay int64
				switch wordpressDefinition.GetVersion() {
				case "v0":
					requeueDelay, err := v0WordpressDefinitionCreated(
						r,
						wordpressDefinition.(*api_v0.WordpressDefinition),
						&log,
					)
					customRequeueDelay = requeueDelay
					operationErr = err
				default:
					operationErr = errors.New("unrecognized version of wordpress definition encountered for creation")
				}
				if operationErr != nil {
					errorMsg := "failed to reconcile created wordpress definition object"
					log.Error(operationErr, errorMsg)
					r.EventsRecorder.HandleEventOverride(
						&tpapi_v0.Event{
							Note:   util.Ptr(errorMsg),
							Reason: util.Ptr(event.ReasonFailedCreate),
							Type:   util.Ptr(event.TypeNormal),
						},
						wordpressDefinition.GetId(),
						wordpressDefinition.GetVersion(),
						wordpressDefinition.GetType(),
						operationErr,
						&log,
					)
					r.UnlockAndRequeue(
						wordpressDefinition,
						requeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
				if customRequeueDelay != 0 {
					log.Info("create requeued for future reconciliation")
					r.UnlockAndRequeue(
						wordpressDefinition,
						customRequeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
			case notifications.NotificationOperationUpdated:
				var operationErr error
				var customRequeueDelay int64
				switch wordpressDefinition.GetVersion() {
				case "v0":
					requeueDelay, err := v0WordpressDefinitionUpdated(
						r,
						wordpressDefinition.(*api_v0.WordpressDefinition),
						&log,
					)
					customRequeueDelay = requeueDelay
					operationErr = err
				default:
					operationErr = errors.New("unrecognized version of wordpress definition encountered for creation")
				}
				if operationErr != nil {
					errorMsg := "failed to reconcile updated wordpress definition object"
					log.Error(operationErr, errorMsg)
					r.EventsRecorder.HandleEventOverride(
						&tpapi_v0.Event{
							Note:   util.Ptr(errorMsg),
							Reason: util.Ptr(event.ReasonFailedUpdate),
							Type:   util.Ptr(event.TypeNormal),
						},
						wordpressDefinition.GetId(),
						wordpressDefinition.GetVersion(),
						wordpressDefinition.GetType(),
						operationErr,
						&log,
					)
					r.UnlockAndRequeue(
						wordpressDefinition,
						requeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
				if customRequeueDelay != 0 {
					log.Info("update requeued for future reconciliation")
					r.UnlockAndRequeue(
						wordpressDefinition,
						customRequeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
			case notifications.NotificationOperationDeleted:
				var operationErr error
				var customRequeueDelay int64
				switch wordpressDefinition.GetVersion() {
				case "v0":
					requeueDelay, err := v0WordpressDefinitionDeleted(
						r,
						wordpressDefinition.(*api_v0.WordpressDefinition),
						&log,
					)
					customRequeueDelay = requeueDelay
					operationErr = err
				default:
					operationErr = errors.New("unrecognized version of wordpress definition encountered for creation")
				}
				if operationErr != nil {
					errorMsg := "failed to reconcile deleted wordpress definition object"
					log.Error(operationErr, errorMsg)
					r.EventsRecorder.HandleEventOverride(
						&tpapi_v0.Event{
							Note:   util.Ptr(errorMsg),
							Reason: util.Ptr(event.ReasonFailedDelete),
							Type:   util.Ptr(event.TypeNormal),
						},
						wordpressDefinition.GetId(),
						wordpressDefinition.GetVersion(),
						wordpressDefinition.GetType(),
						operationErr,
						&log,
					)
					r.UnlockAndRequeue(
						wordpressDefinition,
						requeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
				if customRequeueDelay != 0 {
					log.Info("delete requeued for future reconciliation")
					r.UnlockAndRequeue(
						wordpressDefinition,
						customRequeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
				deletionTimestamp := util.Ptr(time.Now().UTC())
				deletedWordpressDefinition := api_v0.WordpressDefinition{
					Common: tpapi_v0.Common{ID: util.Ptr(wordpressDefinition.GetId())},
					Reconciliation: tpapi_v0.Reconciliation{
						DeletionAcknowledged: deletionTimestamp,
						DeletionConfirmed:    deletionTimestamp,
						Reconciled:           util.Ptr(true),
					},
				}
				_, err = client_v0.UpdateWordpressDefinition(
					r.APIClient,
					r.APIServer,
					&deletedWordpressDefinition,
				)
				if err != nil {
					log.Error(err, "failed to update wordpress definition to mark as deleted")
					r.UnlockAndRequeue(wordpressDefinition, requeueDelay, lockReleased, msg)
					continue
				}
				_, err = client_v0.DeleteWordpressDefinition(
					r.APIClient,
					r.APIServer,
					wordpressDefinition.GetId(),
				)
				if err != nil {
					log.Error(err, "failed to delete wordpress definition")
					r.UnlockAndRequeue(wordpressDefinition, requeueDelay, lockReleased, msg)
					continue
				}
			default:
				log.Error(
					errors.New("unrecognized notifcation operation"),
					"notification included an invalid operation",
				)
				r.UnlockAndRequeue(
					wordpressDefinition,
					requeueDelay,
					lockReleased,
					msg,
				)
				continue
			}

			// set the object's Reconciled field to true if not deleted
			if notif.Operation != notifications.NotificationOperationDeleted {
				reconciledWordpressDefinition := api_v0.WordpressDefinition{
					Common:         tpapi_v0.Common{ID: util.Ptr(wordpressDefinition.GetId())},
					Reconciliation: tpapi_v0.Reconciliation{Reconciled: util.Ptr(true)},
				}
				updatedWordpressDefinition, err := client_v0.UpdateWordpressDefinition(
					r.APIClient,
					r.APIServer,
					&reconciledWordpressDefinition,
				)
				if err != nil {
					log.Error(err, "failed to update wordpress definition to mark as reconciled")
					r.UnlockAndRequeue(wordpressDefinition, requeueDelay, lockReleased, msg)
					continue
				}
				log.V(1).Info(
					"wordpress definition marked as reconciled in API",
					"wordpress definitionName", updatedWordpressDefinition.Name,
				)
			}

			// release the lock on the reconciliation of the created object
			if ok := r.ReleaseLock(wordpressDefinition, lockReleased, msg, true); !ok {
				log.Error(errors.New("wordpress definition remains locked - will unlock when TTL expires"), "")
			} else {
				log.V(1).Info("wordpress definition unlocked")
			}

			// log and record event for successful reconciliation
			successMsg := fmt.Sprintf(
				"wordpress definition successfully reconciled for %s operation",
				strings.ToLower(string(notif.Operation)),
			)
			if err := r.EventsRecorder.RecordEvent(
				&tpapi_v0.Event{
					Note:   util.Ptr(successMsg),
					Reason: util.Ptr(event.GetSuccessReasonForOperation(notif.Operation)),
					Type:   util.Ptr(event.TypeNormal),
				},
				wordpressDefinition.GetId(),
				wordpressDefinition.GetVersion(),
				wordpressDefinition.GetType(),
			); err != nil {
				log.Error(err, "failed to record event for successful wordpress definition reconciliation")
			}
			log.Info(successMsg)
		}
	}

	r.Sub.Unsubscribe()
	reconcilerLog.Info("reconciler shutting down")
	r.ShutdownWait.Done()
}
