// generated by 'threeport-sdk gen' - do not edit

package util

import (
	"fmt"
	nats "github.com/nats-io/nats.go"
	notif "wordpress-threeport-module/internal/wordpress/notif"
)

// Initialize the NATS Jet stream context with controller streams
func InitJetStream(nc *nats.Conn) (*nats.JetStreamContext, error) {
	js, err := nc.JetStream(nats.PublishAsyncMaxPending(256))
	if err != nil {
		return nil, fmt.Errorf("failed to create jetstream context: %w", err)
	}

	// add controller streams
	_, err = js.AddStream(&nats.StreamConfig{
		Name:     notif.WordpressStreamName,
		Subjects: notif.GetWordpressSubjects(),
	})
	if err != nil {
		return nil, fmt.Errorf("could not add stream %s: %w", notif.WordpressStreamName, err)
	}

	return &js, nil
}
