// generated by 'threeport-sdk gen' - do not edit

package routes

import (
	echo "github.com/labstack/echo/v4"
	handlers "wordpress-threeport-module/pkg/api-server/v0/handlers"
	v0 "wordpress-threeport-module/pkg/api/v0"
)

// WordpressDefinitionRoutes sets up all routes for the WordpressDefinition handlers.
func WordpressDefinitionRoutes(e *echo.Echo, h *handlers.Handler) {
	e.GET(v0.PathWordpressDefinitionVersions, h.GetWordpressDefinitionVersions)

	e.POST(v0.PathWordpressDefinitions, h.AddWordpressDefinition)
	e.GET(v0.PathWordpressDefinitions, h.GetWordpressDefinitions)
	e.GET(v0.PathWordpressDefinitions+"/:id", h.GetWordpressDefinition)
	e.PATCH(v0.PathWordpressDefinitions+"/:id", h.UpdateWordpressDefinition)
	e.PUT(v0.PathWordpressDefinitions+"/:id", h.ReplaceWordpressDefinition)
	e.DELETE(v0.PathWordpressDefinitions+"/:id", h.DeleteWordpressDefinition)
}

// WordpressInstanceRoutes sets up all routes for the WordpressInstance handlers.
func WordpressInstanceRoutes(e *echo.Echo, h *handlers.Handler) {
	e.GET(v0.PathWordpressInstanceVersions, h.GetWordpressInstanceVersions)

	e.POST(v0.PathWordpressInstances, h.AddWordpressInstance)
	e.GET(v0.PathWordpressInstances, h.GetWordpressInstances)
	e.GET(v0.PathWordpressInstances+"/:id", h.GetWordpressInstance)
	e.PATCH(v0.PathWordpressInstances+"/:id", h.UpdateWordpressInstance)
	e.PUT(v0.PathWordpressInstances+"/:id", h.ReplaceWordpressInstance)
	e.DELETE(v0.PathWordpressInstances+"/:id", h.DeleteWordpressInstance)
}
