// generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package cmd

import cobra "github.com/spf13/cobra"

// DeleteCmd represents the delete command
var DeleteCmd = &cobra.Command{
	Long:  "Delete a Threeport Wordpress object.\n\n\tThe delete command does nothing by itself.  Use one of the available subcommands\n\tto delete different objects from the system.",
	Short: "Delete a Threeport Wordpress object",
	Use:   "delete",
}

func init() {
	rootCmd.AddCommand(DeleteCmd)
}
