// generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package cmd

import cobra "github.com/spf13/cobra"

// DescribeCmd represents the describe command
var DescribeCmd = &cobra.Command{
	Long:  "Describe a Threeport Wordpress object.\n\n\tThe describe command does nothing by itself.  Use one of the available subcommands\n\tto describe different objects from the system.",
	Short: "Describe a Threeport Wordpress object",
	Use:   "describe",
}

func init() {
	rootCmd.AddCommand(DescribeCmd)
}
