// generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package cmd

import cobra "github.com/spf13/cobra"

// UpdateCmd represents the update command
var UpdateCmd = &cobra.Command{
	Long:  "Update a Threeport Wordpress object.\n\n\tThe update command does nothing by itself.  Use one of the available subcommands\n\tto update different objects from the system.",
	Short: "Update a Threeport Wordpress object",
	Use:   "update",
}

func init() {
	rootCmd.AddCommand(UpdateCmd)
}
