// generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package cmd

import (
	"fmt"
	util "github.com/threeport/threeport/pkg/util/v0"
	"net/http"
	"os"
	"text/tabwriter"
	api_v0 "wordpress-threeport-module/pkg/api/v0"
)

// outputGetWordpressesCmd produces the tabular output for the
// 'tptctl get wordpresses' command.
func outputGetWordpressesCmd(
	v0wordpressInstances *[]api_v0.WordpressInstance,
	apiClient *http.Client,
	apiEndpoint string,
) error {
	writer := tabwriter.NewWriter(os.Stdout, 4, 4, 4, ' ', 0)
	fmt.Fprintln(writer, "VERSION\t NAME\t AGE")
	for _, wordpressInstance := range *v0wordpressInstances {
		fmt.Fprintln(
			writer,
			"v0", "\t",
			*wordpressInstance.Name, "\t",
			util.GetAge(wordpressInstance.CreatedAt),
		)
	}
	writer.Flush()

	return nil
}

// outputGetv0WordpressDefinitionsCmd produces the tabular output for the
// 'tptctl get wordpress-definitions' command.
func outputGetv0WordpressDefinitionsCmd(
	wordpressDefinitions *[]api_v0.WordpressDefinition,
	apiClient *http.Client,
	apiEndpoint string,
) error {
	writer := tabwriter.NewWriter(os.Stdout, 4, 4, 4, ' ', 0)
	fmt.Fprintln(writer, "NAME\t AGE")
	for _, wordpressDefinition := range *wordpressDefinitions {
		fmt.Fprintln(
			writer,
			*wordpressDefinition.Name, "\t",
			util.GetAge(wordpressDefinition.CreatedAt),
		)
	}
	writer.Flush()

	return nil
}

// outputGetv0WordpressInstancesCmd produces the tabular output for the
// 'tptctl get wordpress-instances' command.
func outputGetv0WordpressInstancesCmd(
	wordpressInstances *[]api_v0.WordpressInstance,
	apiClient *http.Client,
	apiEndpoint string,
) error {
	writer := tabwriter.NewWriter(os.Stdout, 4, 4, 4, ' ', 0)
	fmt.Fprintln(writer, "NAME\t AGE")
	for _, wordpressInstance := range *wordpressInstances {
		fmt.Fprintln(
			writer,
			*wordpressInstance.Name, "\t",
			util.GetAge(wordpressInstance.CreatedAt),
		)
	}
	writer.Flush()

	return nil
}
