// generated by 'threeport-sdk gen' - do not edit

package notif

const (
	WordpressStreamName = "wordpressStream"

	WordpressDefinitionSubject       = "wordpressDefinition.*"
	WordpressDefinitionCreateSubject = "wordpressDefinition.create"
	WordpressDefinitionUpdateSubject = "wordpressDefinition.update"
	WordpressDefinitionDeleteSubject = "wordpressDefinition.delete"

	WordpressInstanceSubject       = "wordpressInstance.*"
	WordpressInstanceCreateSubject = "wordpressInstance.create"
	WordpressInstanceUpdateSubject = "wordpressInstance.update"
	WordpressInstanceDeleteSubject = "wordpressInstance.delete"
)

// Get GetWordpressDefinitionSubjects returns the NATS subjects
// for wordpress definitions.
func GetWordpressDefinitionSubjects() []string {
	return []string{
		WordpressDefinitionCreateSubject,
		WordpressDefinitionUpdateSubject,
		WordpressDefinitionDeleteSubject,
	}
}

// Get GetWordpressInstanceSubjects returns the NATS subjects
// for wordpress instances.
func GetWordpressInstanceSubjects() []string {
	return []string{
		WordpressInstanceCreateSubject,
		WordpressInstanceUpdateSubject,
		WordpressInstanceDeleteSubject,
	}
}

// GetWordpressSubjects returns the NATS subjects
// for all wordpress objects.
func GetWordpressSubjects() []string {
	var wordpressSubjects []string

	wordpressSubjects = append(wordpressSubjects, GetWordpressDefinitionSubjects()...)
	wordpressSubjects = append(wordpressSubjects, GetWordpressInstanceSubjects()...)

	return wordpressSubjects
}
