// generated by 'threeport-sdk gen' - do not edit

package versions

import (
	tpapiserver_lib "github.com/threeport/threeport/pkg/api-server/lib/v0"
	"reflect"
	apiserver_v0 "wordpress-threeport-module/pkg/api-server/v0"
	api_v0 "wordpress-threeport-module/pkg/api/v0"
)

// AddWordpressDefinitionVersions adds field validation info and adds it
// to the REST API versions.
func AddWordpressDefinitionVersions() {
	apiserver_v0.WordpressDefinitionTaggedFields[tpapiserver_lib.TagNameValidate] = &tpapiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              tpapiserver_lib.TagNameValidate,
	}

	// parse struct and populate the FieldsByTag object
	tpapiserver_lib.ParseStruct(
		tpapiserver_lib.TagNameValidate,
		reflect.ValueOf(new(api_v0.WordpressDefinition)),
		"",
		tpapiserver_lib.Translate,
		apiserver_v0.WordpressDefinitionTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := tpapiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeWordpressDefinition),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	tpapiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.WordpressDefinitionTaggedFields[tpapiserver_lib.TagNameValidate]

	// add the object tagged fields to the rest API version
	tpapiserver_lib.AddObjectVersion(versionObj)
}

// AddWordpressInstanceVersions adds field validation info and adds it
// to the REST API versions.
func AddWordpressInstanceVersions() {
	apiserver_v0.WordpressInstanceTaggedFields[tpapiserver_lib.TagNameValidate] = &tpapiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              tpapiserver_lib.TagNameValidate,
	}

	// parse struct and populate the FieldsByTag object
	tpapiserver_lib.ParseStruct(
		tpapiserver_lib.TagNameValidate,
		reflect.ValueOf(new(api_v0.WordpressInstance)),
		"",
		tpapiserver_lib.Translate,
		apiserver_v0.WordpressInstanceTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := tpapiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeWordpressInstance),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	tpapiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.WordpressInstanceTaggedFields[tpapiserver_lib.TagNameValidate]

	// add the object tagged fields to the rest API version
	tpapiserver_lib.AddObjectVersion(versionObj)
}
